apiVersion: v1
kind: ReplicationController
metadata:
  name: flaskapp-rc
spec:
  selector:
    name: web
    version: v0.1
  template:
    metadata:
      labels:
        name: web
        version: v0.1
    spec:
      containers:
      - name: whatever
        image: GabrieleDiFlavio/flask-app-example:0.1
        ports:
        - containerPort: 5000
